# Generated by Django 3.0.2 on 2020-01-18 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='publication_date',
            new_name='publication_data',
        ),
    ]
